### ISSUE TITLE
v14 disabled on JF 10.7.7

### ISSUE THREAD

**Issue by charredchar** [jellyfin/jellyfin-plugin-ldapauth#102]
I was having issues getting version 12 set up on my freshly installed Jellyfin Server 10.7.7, I was getting failure to bind errors. I was attempting to use version 14 as it includes options to test and list users but any attempt to install by copying the folder to the plugins directory causes it to return an error, "This plugin has no settings to configure."

Checking the logs, it appears as if the plugin is disabled,
`[2021-12-19 05:32:42.019 -06:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "14.0.0.0" of "LDAP Authentication" `

But within the Jellyfin UI it shows enabled and I can not change it.

**Comment by crobibero** [comment]
v14 is compatible with 10.8, not 10.7.7
