### ISSUE TITLE
memberUid support for admin filter

### ISSUE THREAD

**Issue by cyberb** [jellyfin/jellyfin-plugin-ldapauth#111]
I am using OpenLDAP and it uses memberUid and does not have memberOf feature.

Admin group
```
dn: cn=syncloud,ou=groups,dc=syncloud,dc=org
objectClass: posixGroup
objectClass: top
gidNumber: 1
cn: syncloud
description: Syncloud
memberUid: test
```

Admin user
```
dn: cn=test,ou=users,dc=syncloud,dc=org
objectClass: simpleSecurityObject
objectClass: person
objectClass: inetOrgPerson
objectClass: posixAccount
uidNumber: 10
gidNumber: 10
homeDirectory: test
uid: test
cn: test
sn: test
displayName: test
description: test
```

Something like this user suggested would work fine: https://github.com/jellyfin/jellyfin-plugin-ldapauth/issues/62

LdapAdminFilter: "(&(cn=syncloud)(memberUid=%uid))"

Where uid is username passed into the login form

**Comment by crobibero** [comment]
I'm not sure what issue you're having, but everything should be configurable from the plugin config page.

I personally used OpenLdap with the plugin without issue.

**Comment by cyberb** [comment]
I cannot set admin filter based on memberUid, this does not work because I uave no memberOf:
```
<LdapAdminFilter>(memberOf=cn=syncloud,ou=groups,dc=syncloud,dc=org)</LdapAdminFilter>
```
Do you know how can I change it to support memberUid?
