### ISSUE TITLE
[v14 / JF 10.8.0-b2] Error while saving LDAP plugin config

### ISSUE THREAD

**Issue by robobenklein** [jellyfin/jellyfin-plugin-ldapauth#116]
Getting an error (server 500) and a broken client UI when trying to save the LDAP plugin settings:

```
jellyfin_1    | [05:45:59] [ERR] [99] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /Plugins/958aad66-3784-4d2a-b89a-a7b6fab6e25c/Configuration.
jellyfin_1    | System.Text.Json.JsonException: The converter 'Jellyfin.Extensions.Json.Converters.JsonStringConverter' read too much or not enough. Path: $.PasswordResetUrl | LineNumber: 0 | BytePositionInLine: 663.
jellyfin_1    |    at System.Text.Json.ThrowHelper.ThrowJsonException_SerializationConverterRead(JsonConverter converter)
```

This looked wrong in the request being made:
![image](https://user-images.githubusercontent.com/5423266/164384122-547a5c55-652c-439d-88d5-171bf277d08e.png)

Which might be caused by a missing `.value` on https://github.com/jellyfin/jellyfin-plugin-ldapauth/blob/640cbdb4f6d337e735b0ba8292322a1dd123cd00/LDAP-Auth/Config/configPage.html#L298 ?

**Comment by crobibero** [comment]
That looks like the correct fix. Feel free to make a PR
