### ISSUE TITLE
 LdapException: Size Limit Exceeded (4)

### ISSUE THREAD

**Issue by sphaero** [jellyfin/jellyfin-plugin-ldapauth#139]
It seems this plugin is querying the full ldap database and tries to compare a username to the returned list of users? Correct?

https://github.com/jellyfin/jellyfin-plugin-ldapauth/blob/3a5b07b4d393798170d460f776b3f515cc1a5f86/LDAP-Auth/LDAPAuthenticationProviderPlugin.cs#L382-L396

If that's the case I don't think this how this is supposed to be done. One should do an ldap search for the username attribute matching the username. If that returns a hit one can continue. 

 Am I missing something here? An ldap administrator wouldn't be happy with these queries I guess?

I would help with the code but I'm no C# dev so I would need help setting up a test env?

**Comment by joshuaboniface** [comment]
As far as I can recall, this was done because the LDAP library we were using (the only one I'm aware of, or was at the time, for .NET/C#) didn't allow per-user queries.

It could probably be chunked if required, or if it can do searches for the single user that's definitely ideal.

Test env shouldn't be too complicated: you just need the `dotnet-sdk` package and then run `dotnet build` in the root of the repo to get a plugin file out.

**Comment by sphaero** [comment]
Is that this library? https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard

I'm no LDAP ninja but I think there are multiple ways to verify users. 
* First is to just use a ldap bind call with the user credentials. I think this example does that: https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/master/original_samples/Samples/Bind.cs

*  the other is to either do an anonymous bind or some user bind and search for the user credentials to compare them. I think this example does that: https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/master/original_samples/Samples/VerifyPassword.cs

**Comment by ParhamGhafouri** [comment]
Greetings,

I have this problem on my organization with more than 1000 users to query from LDAP server and still facing "Base Search: Size Limit Exceeded" and "Failure: User Filter: Size Limit Exceeded". was wonder if there is any workaround to fix this problem.

as side note I did change Page Size limit on my LDAP which is active directory but still no luck .

**Comment by sphaero** [comment]
I posted links to the LDAP library of how to do the ldap calls correctly. This needs to be done in the plugin code. If you're familiar with C# a PR is very welcomed I think!

**Comment by ParhamGhafouri** [comment]
Greetings Sphaero, 

Thanks for your respond , unfortunately I don't have that knowledge and therefor can't implement those change into source code, would be nice if you could do us a favor and fix this problem as I've been using this plugin lately and due to increase users that access our media servers we are facing this problem right now.

With kind regards, Parham

**Comment by h3ge** [comment]
> It seems this plugin is querying the full ldap database and tries to compare a username to the returned list of users? Correct?
> 

That's not directly true. It depends on the search filter. In the default Configuration the SearchFilter is "(memberOf=CN=JellyfinUsers,DC=contoso,DC=com)"

If you want to work with huge amount of users permitted to access jellyfin, it would be better to use the username in the SearchFilter.

(&(memberOf:1.2.840.113556.1.4.1941:=CN=MyUserGroup,DC=Groups,DC=dummy,DC=local)(objectClass=user)(sAMAccountName=%ESCAPEDUSERNAME%))


A way could be, that the SearchFilter is dynamically build depending on the login attributes.

**Comment by sphaero** [comment]
That might work as well. Are you saying this is already implemented or that this could be easily implemented?

**Comment by joshuaboniface** [comment]
> Is that this library? [dsbenghe/Novell.Directory.Ldap.NETStandard](https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard)

Yes, that is the correct library.

> I'm no LDAP ninja but I think there are multiple ways to verify users.
> 
>     * First is to just use a ldap bind call with the user credentials. I think this example does that: [dsbenghe/Novell.Directory.Ldap.NETStandard@`master`/original_samples/Samples/Bind.cs](https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/master/original_samples/Samples/Bind.cs?rgh-link-date=2023-02-07T20%3A20%3A44Z)
> 
>     * the other is to either do an anonymous bind or some user bind and search for the user credentials to compare them. I think this example does that: [dsbenghe/Novell.Directory.Ldap.NETStandard@`master`/original_samples/Samples/VerifyPassword.cs](https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/master/original_samples/Samples/VerifyPassword.cs?rgh-link-date=2023-02-07T20%3A20%3A44Z)

The problem with both examples, that we ran into, is that they seem to require knowing the `dn` in advance. The library, at least as far as I recall from when we made this in early 2019, did not have an easy way to search. Perhaps that has changed, but this is why we do the full dump and then search.

It's probably worth revisiting, I'll see if I can spend some time on this over the next few days.

**Comment by h3ge** [comment]
>  I tried to modify LDAP query but still no luck with it.

What query did you use?
I use LDAP very heavy in small to very large environments, maybe I can help with this.

**Comment by ParhamGhafouri** [comment]
I would like to allow users that are member of ALL-Media group able to login into media server , this group is about 5000 members , this is what I'm using right now :

(memberOf=CN=Org-AllMedia,OU=Departments,OU=Security,OU=Domain Groups,DC=local,DC=com)

**Comment by joshuaboniface** [comment]
This actually ended up being fairly easy. It just wasn't obvious how best to use the `Search()` method.

I have an improved search system incoming.

**Comment by joshuaboniface** [comment]
And, it's not, because I was working from a much older version of the plugin that didn't try to do stuff like case-insensitive name searching. That will never work with a filter-based approach and will need to be removed.

**Comment by h3ge** [comment]
> And, it's not, because I was working from a much older version of the plugin that didn't try to do stuff like case-insensitive name searching. That will never work with a filter-based approach and will need to be removed.

Why? Ldap search is case insensitive in most cases. (as long it's not a IA5String), usually you need to work with matching rules if you want it case sensitive.

**Comment by joshuaboniface** [comment]
@h3ge Yep, I realized that - have a fairly robust implementation incoming (just ignore those various force-pushes above lol).

**Comment by ParhamGhafouri** [comment]
> @h3ge Yep, I realized that - have a fairly robust implementation incoming (just ignore those various force-pushes above lol).

Greetings Joshua,

Glad that you are working to solve this problem and looking forward to see new release anytime soon
