### ISSUE TITLE
User not given administrator rights on first login

### ISSUE THREAD

**Issue by adamshand** [jellyfin/jellyfin-plugin-ldapauth#145]
Hello,

Thanks for the great plugin to a great open source project! :-)  Hoping someone can help me with an issue ...

I'm running LLDAP 0.4.3, LDAP-Auth 17.0.0.0, and Jellyfin 10.8.10 using Docker.  

The LDAP plugin seems to be working and configured correctly.  I can log into Jellyfin with any LLDAP user and everything works as expected ... EXCEPT that admin permissions are not granted.

In the Jellyfin LDAP plugin settings:

When I click "Save and Test LDAP Server Settings" I get:

> Connect (Success); Bind (Success); Base Search (Found 4 Entities)

When I click "Save and Test LDAP Filter Settings": I get:

> Found 4 user(s), 2 admin(s)

These both match what I expect.

However when I log into Jellyfin with one of the admin users they are not granted admin access to Jellyfin.  If I then manually give them admin rights in Jellyfin - and logout/login - admin access is removed (as expected for a non-admin user).

I'm following the instructions here: https://github.com/lldap/lldap/blob/main/example_configs/jellyfin.md

Any assistance would be much appreciated.

Thanks,
Adam.

![image](https://github.com/jellyfin/jellyfin-plugin-ldapauth/assets/130651/6356ca26-ba83-4276-8b0f-c5fe5df3bef2)

**Comment by gdunstone** [comment]
I worked this out!

Change your admin basedn to whatever you use for your user basedn

**Comment by adamshand** [comment]
That totally works, thank you!!  

I'll update the LLDAP documentation so that you hopefully don't get the same questions again ...
