### ISSUE TITLE
Enable Referral Following

### ISSUE THREAD

**Issue by KeithGraber** [jellyfin/jellyfin-plugin-ldapauth#15]
Hello,

I think I'm close to getting the plugin configured correctly for my environment, but I've run into the following:

LdapReferralException: Search result reference received, and referral following is off (10) Referral

I'm looking for valid users in an AD group (in this case the "All Users" email group) that is in a different OU than where the user accounts are.

Searching, I found the following page that (I believe) explains the issue I'm having:
[https://stackoverflow.com/questions/46052873/a-list-of-all-users-ldap-referral-error-ldapreferralexception](https://stackoverflow.com/questions/46052873/a-list-of-all-users-ldap-referral-error-ldapreferralexception)

Also, are there any issues with account names with spaces?  for example FirstName (space) LastName

Hope I provided the needed information, but if not please ask and I'll get more.

Thanks!

**Comment by joshuaboniface** [comment]
There are, usernames in Jellyfin can't contain spaces, or generally any non-alphanumeric character.

**Comment by KeithGraber** [comment]
Thanks for the username info.

I closed this ticket because I saw it was a duplicate of issue #9
