### ISSUE TITLE
Password Reset reports try again from your home network

### ISSUE THREAD

**Issue by adyanth** [jellyfin/jellyfin-plugin-ldapauth#156]
My Jellyfin instance is behind a reverse proxy. I would like for anyone to be able to request a password reset. Neither URL nor LDAP password resets work.

**Comment by crobibero** [comment]
The LDAP plugin doesn't support password resets.

**Comment by adyanth** [comment]
<img width="611" alt="Screenshot 2024-03-08 at 6 13 11 PM" src="https://github.com/jellyfin/jellyfin-plugin-ldapauth/assets/33192449/eba071d8-3649-432a-ac9f-7e750bb66a6a">

This screenshot is from the LDAP config page @crobibero. What do you mean by it does not support password resets?

**Comment by crobibero** [comment]
Password change is not password reset. 

This function (and others) would need to be populated for it to work. 

https://github.com/jellyfin/jellyfin-plugin-ldapauth/blob/a866c85e7c34cb5848c287586987fbe4761dd250/LDAP-Auth/LDAPAuthenticationProviderPlugin.cs#L512
