### ISSUE TITLE
Add support for secondary server for failover

### ISSUE THREAD

**Issue by FDrebin** [jellyfin/jellyfin-plugin-ldapauth#20]
Hello,

I am using the plugin for Active Directory and it works great, I am curious if it would be possible to add a second optional field for a secondary failover domain controller in the event the primary is not reachable.

**Comment by paranoyed** [comment]
I'm guessing you have a DNS entry pointing to the AD Server?
If so you could archive a failover scenario by adding multiple DNS Entries that point to the same AD server and using the host name that points to both servers.

Example: 
ad IN A 10.10.10.10
ad IN A 10.10.10.11

The DNS server would give back both entries and the LDAP-plugin **should** use the first one that responds.

I have **not** tested this for this plugin but I use this method with other Applications where defining multiple servers is not possible.

**Comment by army1349** [comment]
You can do that right now. Just fill LDAP Server field like:
`server1.domain server2.domain`

**Comment by dkanada** [comment]
@FDrebin it sounds like this feature already exists in LDAP so we can close this?

**Comment by FDrebin** [comment]
> 
> 
> @FDrebin it sounds like this feature already exists in LDAP so we can close this?

Yes I believe it can! Thank you.
