### ISSUE TITLE
Header Authentication

### ISSUE THREAD

**Issue by Ornias1993** [jellyfin/jellyfin-plugin-ldapauth#25]
Although slightly byond the scope of this plugin, it would insanely improve it usefullness if it would include Header Authenication.

What is header auth?
Proxy does auth, if successfull sets header "X-Forwarded-User" = "username"
Webserver gets username and logs in the user without password.

**Comment by Nautigsam** [comment]
I think this feature should be implemented in Jellyfin server. In the case of a header authentication the request should not pass by the plugin.

**Comment by crobibero** [comment]
This would be a feature for server, not for the plugin
