### ISSUE TITLE
User creation on signin fails from external (non LAN) connections

### ISSUE THREAD

**Issue by bluesaxman** [jellyfin/jellyfin-plugin-ldapauth#26]
I'm curious if the plugin is running from the backend or from the web frontend for authentication. I have it configured to use a local address, but this seems to fail, I've not been able to test locally today, but externally it fails. 

 ```
  <LdapServer>192.168.1.61</LdapServer>
  <LdapBaseDn>dc=example,dc=com</LdapBaseDn>
  <LdapPort>390</LdapPort>
  <LdapSearchAttributes>uid,cn</LdapSearchAttributes>
  <LdapUsernameAttribute>cn</LdapUsernameAttribute>
  <LdapSearchFilter>objectClass=person</LdapSearchFilter>
  <LdapAdminFilter>enabledService=JellyfinAdministrator</LdapAdminFilter>
  <LdapBindUser>cn=manager,dc=example,dc=com</LdapBindUser>
  <LdapBindPassword>*******</LdapBindPassword>
  <CreateUsersFromLdap>true</CreateUsersFromLdap>
  <UseSsl>false</UseSsl>  #If its connecting from the front end then I'll need to set this up
```

When trying to sign in with an LDAP user that does not yet have an account the following message is given:

> Connection Failure
> We're unable to connect to the selected server right now. Please ensure it is running and try again.

This is what leads me to think that the plugin is trying to contact LDAP from the frontend UI and not the backend, if I'm mistaken I apologize for opening the issue, though I would love some guidance if I'm just setting this up incorrectly.

**Comment by HudsonProdigy** [comment]
I am also having troubles with this plugin, i can not get it to work with my windows server 2016 Ad. when i have more time i have to dig into it more. but the plugin is written in c# and runs server side. This much i know. I think the error you are seeing is generic error for failed authentication attempt. if you look in your logs you should be able to see more verbose error and maybe figure out what actually issue is.

**Comment by bluesaxman** [comment]
Don't know why I didn't think to check the longs before opening an issue. It turned out there was a syntax error in my config, Authentication now works both with accounts that have never logged in and with accounts that have previously logged in. Both on forign networks and the local network. 

I did notice though a repeated error ```Error processing request: "Access token is required."```
But that already has an issue opened for it and so I'm betting it doesn't have anyting to do with mine. I'll close this for now, since it seems the issue was between the seat and keyboard in my case.
