### ISSUE TITLE
No log output in Jellyfin 10.5

### ISSUE THREAD

**Issue by LasseF-H** [jellyfin/jellyfin-plugin-ldapauth#28]
It seems Jellyfin has changed the way logs are managed, and since the output there is no ouput regarding LDAP authentification. The only related output is this:
`[2020-03-09 17:08:16.344 +00:00] [ERR] Error processing request: "[10.0.4.4] Invalid username or password entered."
`
However, I don't know if it's because the plugin simply isn't being invoked, or if its only the logging. As my configuration wasn't working before the update.

**Comment by LasseF-H** [comment]
It seems to be related to this: https://github.com/jellyfin/jellyfin/issues/2540

**Comment by dkanada** [comment]
@mark-monteiro will this be fixed with your logging pull requests?

**Comment by mark-monteiro** [comment]
@LasseF-H do you have a custom logging configuration? Can you attach it here?

**Comment by LasseF-H** [comment]
I have since downgraded to 10.4 to get LDAP authentication working again. But it wasn't custom, just a line from the latest log file in /var/log/jellyfin. Each login attempt only resulted in the line from my initial comment.

**Comment by mark-monteiro** [comment]
@LasseF-H can you clarify what your issue is? Are you seeing no log output from the server at all, or you're just missing some logging from the LDAP plugin specifically? If the latter, what logging output from the plugin do you normally see that you are not seeing now?

**Comment by mark-monteiro** [comment]
@LasseF-H can you clarify what your issue is? Are you seeing no log output from the server at all, or you're just missing some logging from the LDAP plugin specifically? If the latter, what logging output from the plugin do you normally see that you are not seeing now?

**Comment by mark-monteiro** [comment]
@LasseF-H can you clarify what your issue is? Are you seeing no log output from the server at all, or you're just missing some logging from the LDAP plugin specifically? If the latter, what logging output from the plugin do you normally see that you are not seeing now?

**Comment by LasseF-H** [comment]
I figured it out, turns out there wasn't an issue. I just hadn't configured my LDAP properly.
