### ISSUE TITLE
Won't accept credentials of LDAP user

### ISSUE THREAD

**Issue by PureTryOut** [jellyfin/jellyfin-plugin-ldapauth#31]
I'm trying to setup this plugin currently. Installed correctly, configured connection info through the web UI with the same data as is working fine on other applications connecting to LDAP.

However, no matter what I do, when trying to login with a user available on the LDAP instance, Jellyfin just reports Invalid username or password.

The log doesn't indicate it's even checking LDAP...

```
Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: [<ip redacted>] Invalid username or password entered.
```

**Comment by arantes555** [comment]
@PureTryOut There is currently a bug with Jellyfin v10.5.x . See https://github.com/jellyfin/jellyfin/issues/2654 https://github.com/jellyfin/jellyfin-plugin-ldapauth/issues/29 https://github.com/jellyfin/jellyfin-plugin-ldapauth/pull/30 .

It works fine with Jellyfin v10.4.x

**Comment by PureTryOut** [comment]
Oh interesting, thanks for your answer! I'll wait for a new release then.

**Comment by arantes555** [comment]
@PureTryOut As it's explained in a few of the comments of these issues, it's actually only adding new users with LDAP which fails. If the user already exists, they can connect with LDAP. So, as a workaround, you can just create the users manually in the dashboard beforehand. It's far from perfect but actually quite usable despite the bug ^^

**Comment by PureTryOut** [comment]
Hmm, yes guess that's doable. I only have 2 or 3 users anyway ;)

Thanks. Will close this issue in favor of the others.

**Comment by PureTryOut** [comment]
Actually, @arantes555, what would I do with the password field then in the Jellyfin dashboard? Can that just be left empty?

**Comment by arantes555** [comment]
@PureTryOut You can just put an arbitrary password, it wont be used anyway.
