### ISSUE TITLE
Add groups discovery

### ISSUE THREAD

**Issue by Nautigsam** [jellyfin/jellyfin-plugin-ldapauth#33]
First of all, thank you for your work on this project. This has been very useful to me. Though I have one feature request to increase the flexibility of the plugin.

Currently we only look at the user's fields for user and admin filters. I think it is common to define groups with "member" fields. In that case we can not filter users by only looking at user's fields.

I think we should add the following settings :
- LDAP Base DN for group searches (e.g. "ou=groups,dc=local,dc=domain")
- LDAP Group Member Attribute (e.g. "member")

Finally, a setting should allow to specify if we want to filter on the group's fields or on the user's fields (current behaviour).

**Comment by Ciapa** [comment]
You can just configure the filters accordingly. Here's how I've defined them:

User filter:
`(memberOf=cn=jellyfin.user,ou=permissions,dc=example,dc=com)`

Admin filter:
`(memberOf=cn=jellyfin.admin,ou=permissions,dc=example,dc=com)`

**Comment by Nautigsam** [comment]
Well your filter is still applied on user entries. It works if you define user-group relationship on the user side (with `memberOf` field). But it does not work if you define the relationship on group side with `member` field, and this is a common pattern.

If I want to create a `jellyfin` group to restrict access to some users, I do not want to edit every user to add a `memberOf` field. I prefer to add as many `member` fields as I need on the group.

**Comment by Ciapa** [comment]
`memberOf` is a virtual field, you don't have to set it manually.
See https://ldapwiki.com/wiki/MemberOf

Depending on what server you use, you might have to enable it first.

**Comment by Nautigsam** [comment]
I didn't know that, thank you for the hint.
