### ISSUE TITLE
LDAP Auth username is case sensitive

### ISSUE THREAD

**Issue by ossiozac** [jellyfin/jellyfin-plugin-ldapauth#34]
Hello,

Thank you for the plugin, it's great not to have to have Emby Premium.

I am using this with MS Active Directory. When logging in, the username is case sensitive and I can't disable that, I believe that this should not be default behaviour as in LDAP it is generally all case insensitive.

My config is below:

```
LDAP Base DN for searches:
OU=Users,OU=HQ,DC=ad,DC=domain,DC=co,DC=uk

LDAP Attributes:
sAMAccountName, mail

LDAP Name Attribute::
sAMAccountName

LDAP User Filter:
(&(memberof:1.2.840.113556.1.4.1941:=CN=HQUsers,OU=Groups,OU=HQ,DC=ad,DC=domain,DC=co,DC=uk)(objectCategory=person)(objectClass=user)(!(objectclass=computer)))

LDAP Admin Filter:
(memberof:1.2.840.113556.1.4.1941:=CN=MediaAdmins,OU=Groups,OU=HQ,DC=ad,DC=domain,DC=co,DC=uk)

LDAP Bind User:
CN=Jellyfin,OU=Service Accounts,OU=HQ,DC=ad,DC=domain,DC=co,DC=uk
```

Also the error when a user who doesn't exist or the password is wrong isn't very helpful for end users, maybe it could be a normal invalid username or password?

```
Connection Failure
We're unable to connect to the selected server right now. Please ensure it is running and try again.
```

Many thanks

**Comment by ossiozac** [comment]
I think this is the issue...

https://github.com/jellyfin/jellyfin-plugin-ldapauth/blob/7ea822ea69bfab833f58becf3ab4492fb740e135/LDAP-Auth/LDAPAuthenticationProviderPlugin.cs#L96

After a little Google maybe this will work?

```c#
if (string.Equals(username, name, StringComparison.CurrentCultureIgnoreCase))
```

**Comment by pjeanjean** [comment]
Just wanted to add that the fix proposed by @ossiozac works fine on my setup.
