### ISSUE TITLE
[bug] Allow To Turn Off SSL Cert Verify

### ISSUE THREAD

**Issue by sheckandar** [jellyfin/jellyfin-plugin-ldapauth#38]
- Windows 10 64 bit
- JellyFin 10.5.5 fresh install
- Trying to login with AD user
- Samba 4.9.8 as AD DC controller, single domain
- Default SAMBA generated SSL cert (self-signed)

**Error:**
_

> [2020-06-12 22:21:47.919 -06:00] [ERR] [15] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.100:8096/Users/authenticatebyname"
> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
>    at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.Authenticate(String username, String password)
>    at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
>    at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
>    at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
>    at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
>    at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
>    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
>    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
>    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

_

Please add a setting to disable SSL validation. Since this is an internal domain only, I won't be adding a valid CA validated certificate.

SAMBA is running with Server 2008 level and requires SSL to connect to the controller so there is no other option to use.

**Comment by crobibero** [comment]
This is already fixed with master, but no release was created. If you build it yourself you should see the option
