### ISSUE TITLE
All Settings Disappear in 6.0 on a reboot

### ISSUE THREAD

**Issue by charredchar** [jellyfin/jellyfin-plugin-ldapauth#42]
Running Plugin version 6.0 on server version 10.4.3, after entering all of my settings then restarting the server all of the settings disappear. I also noticed if I leave any settings blank, including the field LDAP Bind User which can be blank in some cases, it'll enter examples automatically instead of just leaving it blank. The auto-filled LDAP Admin Filter option also seems to be an incorrect example: "(enabledService=JellyfinAdministrator"

**Comment by crobibero** [comment]
Does this still happen with LDAP v9 and Jellyfin 10.6.1?

**Comment by charredchar** [comment]
Sorry for the delay but I am not really able to test this as it is currently running and I am not really willing to update without knowing it will continue to work.

**Comment by crobibero** [comment]
Ok, I will consider this closed as I use this plugin every day with 10.6.x

**Comment by charredchar** [comment]
So thought I would go ahead and update in hopes that everything was fixed from your comment.

It is not fixed, it is worse now, 9.0 on JF 10.6.3 does not save settings at all. Thanks, completely broke my JF server again.
