### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Window-Hero** [jellyfin/jellyfin-plugin-ldapauth#47]
Since the current release version (6.0) of the plugin is (apparently) incompatible with the current version of Jellyfin (10.6.0), might it be time to push a new release and add it to the catalogue repo?

**Comment by crobibero** [comment]
As of 10.6 there is a new repository: https://repo.jellyfin.org/releases/plugin/manifest-stable.json
Currently v8.0.0.0 is published there, and we are working on getting v9.0.0.0 uploaded. The automated deployments haven't been set up with 10.6 compatibility yet.

**Comment by crobibero** [comment]
v9.0.0.0 has been pushed to the repo
