### ISSUE TITLE
Add LDAP group filter for FreeIpa

### ISSUE THREAD

**Issue by jhayet** [jellyfin/jellyfin-plugin-ldapauth#62]
Hi,

I currently use jellyfin-plugin-ldapauth for my jellyfin instance and the authentication works perfectly well ! (it is great to read that sometimes huh ?)
But (yeah, sorry), when LDAP like FreeIpa is used, the information about groups isn't stored into user's CN (with memberOf attribute), it's actually the opposite : the group contains users included to.

For example, if i want to know if my user is allowed to use my jellyfin instance, i have to search in my LDAP groups with the memberUid: attribute.

User looks like that :
```
# jdoe, users, accounts, lan.example.com
dn: uid=jdoe,cn=users,cn=accounts,dc=lan,dc=example,dc=com
displayName: John Doe
**uid: jdoe**
```

And group looks like that :
```
# Users, groups, compat, lan.example.com
dn: cn=leechers,cn=groups,cn=compat,dc=lan,dc=example,dc=com
objectClass: posixGroup
objectClass: ipaOverrideTarget
objectClass: ipaexternalgroup
objectClass: top
gidNumber: 118000022
memberUid: otherLeecher
memberUid: newPirate
**memberUid: jdoe**
cn: leechers
```

So it is possible to authenticate through LDAP, but i can't specify neither the admin filter nor the group restriction.

Do you think it would be possible to add a group filter section in your plugin ?
It should be able to use the previous successfully authenticated ldap user and do a new research with another LDAP filter, and the admin could specify the dn group to look for AND the attribute which should contain the uid user.

In my case "(&(cn=leechers)(memberuid=jdoe))" or two textArea, first with the group cn, second with the attribute which has to match previously authenticated uid.

Thanks.

**Comment by stove-panini** [comment]
I'm using CentOS Identity Management (FreeIPA 4.9) and the memberOf attribute is part of the user search.

`ldapsearch -Y GSSAPI -b 'cn=users,cn=accounts,dc=lab,dc=trashnet,dc=xyz' '(memberOf=cn=JellyfinUsers,cn=groups,cn=accounts,dc=lab,dc=trashnet,dc=xyz)'`
```
SASL/GSSAPI authentication started
SASL username: stephen@LAB.TRASHNET.XYZ
SASL SSF: 256
SASL data security layer installed.
# extended LDIF
#
# LDAPv3
# base <cn=users,cn=accounts,dc=lab,dc=trashnet,dc=xyz> with scope subtree
# filter: (memberOf=cn=JellyfinUsers,cn=groups,cn=accounts,dc=lab,dc=trashnet,dc=xyz)
# requesting: ALL
#

# stephen, users, accounts, lab.trashnet.xyz
dn: uid=stephen,cn=users,cn=accounts,dc=lab,dc=trashnet,dc=xyz
memberOf: cn=ipausers,cn=groups,cn=accounts,dc=lab,dc=trashnet,dc=xyz
memberOf: cn=sysadmins,cn=groups,cn=accounts,dc=lab,dc=trashnet,dc=xyz
memberOf: ipaUniqueID=88000682-5525-11eb-ae23-002324d98b03,cn=sudorules,cn=sud
 o,dc=lab,dc=trashnet,dc=xyz
memberOf: cn=jellyfinusers,cn=groups,cn=accounts,dc=lab,dc=trashnet,dc=xyz
givenName: Stephen
sn: Panicho
uid: stephen
cn: Stephen Panicho
displayName: Stephen Panicho
...
```

So, in Jellyfin, if I set the **LDAP Base DN for Searches** to `cn=users,cn=accounts,dc=lab,dc=trashnet,dc=xyz` and **LDAP User Filter** to `(memberOf=cn=JellyfinUsers,cn=groups,cn=accounts,dc=lab,dc=trashnet,dc=xyz)`, the group restriction works as expected.

**Comment by jhayet** [comment]
Arg… indeed, it works !
Thanks for your help.
