### ISSUE TITLE
LDAP Authentication plugin won't install

### ISSUE THREAD

**Issue by ccellist** [jellyfin/jellyfin-plugin-ldapauth#69]
# System 
* OS: Ubuntu 18.04
* Jellyfin Version: 10.6.4 (dockerized)
* LDAP Plugin version: 10.0.0
* I'm using OpenLDAP standard package provided by Ubuntu

# Symptoms
Attempting to install the LDAP Auth plugin through the dashboard fails with the following error:

```
jellyfin                | [01:00:01] [ERR] [42] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://192.168.201.3:8097/Packages/Installed/LDAP Authentication?Assemb
lyGuid=958aad66-3784-4d2a-b89a-a7b6fab6e25c&version=10.0.0.0
jellyfin                | MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: LDAP Authentication
jellyfin                |    at MediaBrowser.Api.PackageService.Post(InstallPackage request)
jellyfin                |    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
jellyfin                |    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken ca
ncellationToken)
jellyfin                |    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationTok
en)
```
The repository currently in used is the default, https://repo.jellyfin.org/releases/plugin/manifest-stable.json and I can get to the relevant plugin files using my browser at https://tor1.mirror.jellyfin.org/releases/plugin/ldap-authentication/.

Previously I had installed a custom-built fork of this plugin to allow StartTLS connections against my LDAP server but that isn't working in the new version of Jellyfin either (may file a separate bug for that). I'd like to install the regular version of the plugin to see if the StartTLS fix that made it to master ever got released so I can use LDAP again.

Thanks.

**Comment by crobibero** [comment]
v10 is for 10.7
v9 is for 10.6

https://github.com/jellyfin/jellyfin/issues/4688
